
apiVersion: metallb.metallb.io/v1beta1
kind: AddressPools
metadata:
  name: config-sample
  namespace: metallb-system
spec:
  address-pools:
  - name: default
    protocol: bgp
    addresses:
    - 172.18.255.100/24
    bgp-advertisements:
    - aggregation-length: 32
      localpref: 100
      communities:
      - no-advertise
    - aggregation-length: 24

---

apiVersion: metallb.metallb.io/v1beta1
kind: Peers
metadata:
  name: config-sample
  namespace: metallb-system
spec:
  peers:
  - peer-address: 10.0.0.1
    peer-asn: 64501
    my-asn: 64500
    router-id: 10.10.10.10
    node-selectors:
    - match-expressions:
      - key: kubernetes.io/hostname
        operator: In
        values: [hostA, hostB]

---

apiVersion: metallb.metallb.io/v1beta1
kind: BgpCommunities
metadata:
  name: config-sample
spec:
  bgp-communities:
      no-advertise: 65535:65282