apiVersion: metallb.metallb.io/v1beta1
kind: AddressPools
metadata:
  name: addresspools-sample
  namespace: metallb-system
spec:
  address-pools:
  - name: default
    protocol: layer2
    addresses:
    - 172.18.255.100-172.18.255.200
