apiVersion: metallb.metallb.io/v1beta1
kind: Peers
metadata:
  name: peers-sample
  namespace: metallb-system
spec:
  peers:
  - peer-address: 10.0.0.1
    peer-asn: 64501
    my-asn: 64500
    router-id: 10.10.10.10
    node-selectors:
    - match-expressions:
      - key: kubernetes.io/hostname
        operator: In
        values: [hostA, hostB]
