language: go
go_import_path: go.universe.tf/metallb
install:
- go get github.com/Masterminds/glide
- go get github.com/golang/lint/golint
script:
- glide install
- go install -v go.universe.tf/metallb/controller go.universe.tf/metallb/bgp-speaker
- go test $(glide novendor)
- go vet $(glide novendor)
- glide novendor | xargs -n1 golint
os:
- linux
go:
- 1.8
- 1.9
jobs:
  include:
  - stage: deploy
    if: type = push
    go: 1.9
    install: true
    script: printenv TRAVIS_BRANCH
    deploy:
    - provider: script
      script: go run dockerfiles/trigger_build.go
      on:
        all_branches: true
  - stage: test on tip
    go: tip
env:
  global:
  - # tutorial container
    secure: ABjUCbtGLULq8tJB050CHUxh/97XhqomLmuGo+3J8XjwRV7TCybZIZ6KQhKW3353FjnMVKzjcVBMceGGNCJyM1AkXant528BPEm4TZFsL6f2XdLj66uGv+8JL9A0+50IFYQovwUsMYUiH8D3nOTBKR0K1kNLrnRXSSDk04zjJgGbFwyz7Yr/aTEWUA3lphKy+Vb1SK3n1HGZXtkkME5xSfa6p46sjzVu4JoLKwOe2qR2zLS394jcQfUVLKSLsQ1ncEjYZfgx7PGa6MKju1Np0h08UwdLRFepotu/EITKLKyqdazy+EZT34/0EGL2gMZoCc+4UYFqzyZHwceSweOpWFs4MjTiTdTIuZhYboymjCUaDaKSeIsN2kQfmRdTjilQwFxJfdWxirCwkd4ebR4dqq/3iX8yLnGElSlPA5NGLgqb7FC49PYaEYj4xMA6OHPCr0vuefyVsfOwS2FphuKsDQKCDIcV949inT9/PIMaEPJqqXcl9Qwyyk9dQlPHBIVp3e0JTCPhAqfUG2mgUVLypuYtzlz6V4LO4ppl1UOtgJRdo2R+LBYKvq+NkjusaiYWVMUSlHeWtifBCXeax+qXJUgP4ktXfTX0qGfJtxSRzrI5oCLj8WL/LUyLXlwO/m5C3p8ORISLTUasshFsHR2w3sIm+6FDYl3nvpWH4cfBo4M=
  - # controller
    secure: sT0z6sz5fu3TvKy/aK0vvOZtKi4WP6q+9KBW9u3LfVqo7udX90K8dJC7UifBWEScsgViZLVcmYbhR8pplY7Lbsv7konSNGgdglVv9ICrE7/kQHhuLqa3OfFhxRZ/WKEk8eqsOjMAT11BwL4Sx3xYNrchQnNDHeEHFUoA4Csm3I+GvvXg3AmPOO/L1afPSltSs0psx7DbxCcakeg0YRhwYr5wLZVzoYlIAnnIFbxYuEyvAB6sfCo94gH8BfTuCdNS5V1cSlEQXCNY38xN0IcT5ujnkB1dHyN9QL/GBWpaPJmB25Gtyq06+dQro8c/1qQdNXKoFtboYZeeviQZrLnwwCWuRnVYJOvgUwiKL6ooSGt11tRTxVLCIZ9Tb9pOzCUBQeACGm8cV5ZR2lIwBhtch4FWvQtPJl9x6TvTOFhk1lN8m5kBIIh/ACdXhZw8CXDX0i2N+QErMBqXMomBS0NKcWzAEfv3qujz5YE4rZCNUzVBTeiH3cOGcMPAgW735xMJ46dfiztVFjnrQjdGy3PtdkDo1tAkkkaO35b8EhnVXYg9i8GpE4FfE/pI9PKQDgmOd1re+IHsY/d5PnFAq7RIaPVzQEhmAGbrvhENt/Q3Xu0PMfFX2w5/5ZlQyDjJ6L+RX4rx3lOS0alhdjDcZa2d9yYU5MzW1mgd8do6Ezl/3r8=
  - # BGP speaker
    secure: oSYt1mELId8WUukOdJuv/3c4LzIMULUcLfXt9UefL4LEcDqUjWWmEd/+XMvPeAVb4MN/g9HU4uo6zpYPdpkvWsYTzoOux/72J0tEa4h9t3hqcKN1WWStiHMwbpgsovY7cBeE2k/XxvUktxRgDi+6P4ADAcJq4zboELArDzgMgmBDOVdqXQWV01WAeKo0V7CPr1tbrpvSYHGwR176fDiy9z2fl38MxVXp5Uo51J9T7Qx/SlBQi595azj4PrJecMhXTSvjXD0LjL9JitIJEILX88fJisGWB3IezpD5j4MCfOWIrqnuVWKdQ8aAUWTnzJoMy/ub1wiO1ymLUqs9KHGsoDizgsU2CI343PSB3AlavOHLdHTleEf+0pEOMAJQIop/FBDOmPH9JlQBlR1DrFrrgQQ2KPOYEDqF7KrkUVGKBldAAFg7KzHzcL7sE9FusP6NVB1Qd7gnvLFNhtQ13tVpLb9ka+LzeMnJ/M7LtJd6EZbxrYTv4M0zQ9RVlrc5K4rw4lhdmxeQyAMc/4idRmsPF3RSb79He74B3YjWlLXEFzBoBh5W9SH0KeCxuZzhtA+QOgPif8X3pIcp+2HYN+y3jXj9QyfxMUDgC7nDvh+qYM/beHTjn+v4OaxAO/4FrKhpbJBXxz+WpVJ9ur8OQmldtWf6IOZr27bqPKLhxd68l+A=
