apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "metallb.fullname" . }}-speaker
  labels:
    {{- if not .Values.manifest }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "metallb.chart" . }}
    {{- end }}
    app: {{ template "metallb.name" . }}
    component: speaker
spec:
  selector:
    matchLabels:
      app: {{ template "metallb.name" . }}
      component: speaker
      {{- if not .Values.manifest }}
      release: {{ .Release.Name | quote }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- if not .Values.manifest }}
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: {{ template "metallb.chart" . }}
        {{- end }}
        app: {{ template "metallb.name" . }}
        component: speaker
{{- if .Values.prometheus.scrapeAnnotations }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7472"
{{- end }}
    spec:
      serviceAccountName: {{ template "metallb.speakerServiceAccountName" . }}
      terminationGracePeriodSeconds: 0
      hostNetwork: true
      containers:
      - name: speaker
        image: {{ .Values.speaker.image.repository }}:{{ .Values.speaker.image.tag }}
        imagePullPolicy: {{ .Values.speaker.image.pullPolicy }}
        args:
        - --port=7472
        - --config={{ template "metallb.configMapName" . }}
        env:
        - name: METALLB_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: monitoring
          containerPort: 7472
        resources:
{{ toYaml .Values.speaker.resources | indent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - all
            add:
            - net_raw
    {{- with .Values.speaker.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.speaker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.speaker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
