apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    {{ range $entry := .AddressPools -}}
    - name: {{ $entry.Name }}
      protocol: {{ $entry.Protocol }}
      addresses:

      {{ range $a := $entry.Addresses -}}
      - {{ $a }}
      {{ end -}}

     {{ $advlen := len $entry.BgpAdvertisements }} {{ if gt $advlen 0 }}
      bgp-advertisements:
      {{ range $adv := $entry.BgpAdvertisements -}}

        {{ if ne $adv.AggregationLength 0 }}
          - aggregation-length: {{ $adv.AggregationLength }}
        {{ end }}

        {{ if ne $adv.LocalPref 0 }}
          localpref: {{ $adv.LocalPref }}
        {{ end }}

        {{ $commlen := len $adv.Communities }} {{ if gt $commlen 0 }}
          communities:
          {{ range $comm := $adv.Communities -}}
            - {{ $comm }}
          {{ end -}}

        {{ end }}

      {{ end -}}
    {{ end }}
    {{ end -}}